
INSERT INTO `classifier` (id,category,tag_lv,tag_en,tag_ru) VALUES (1,'danceskill','Balles dejas',NULL,NULL),
 (2,'danceskill','Latīņamerikas dejas',NULL,NULL),
 (3,'danceskill','Streatdance','Streatdance',NULL),
 (4,'danceskill','Break dance','Break dance',NULL),
 (5,'danceskill','Hip-hop','Hip-hop',NULL),
 (6,'danceskill','Show dance','Show dance',NULL),
 (7,'danceskill','House dance','House dance',NULL),
 (8,'danceskill','Reggae','Reggae',NULL),
 (9,'danceskill','Dancehall','Dancehall',NULL),
 (10,'danceskill','Locking','Locking',NULL),
 (11,'danceskill','Popping','Popping',NULL),
 (12,'danceskill','Balets',NULL,NULL),
 (13,'musicskill','Akordeons',NULL,NULL),
 (14,'musicskill','Bajāns',NULL,NULL),
 (15,'musicskill','Lociņinstrumenti',NULL,NULL),
 (16,'musicskill','Pūšamie',NULL,NULL),
 (17,'musicskill','Sintezators',NULL,NULL),
 (18,'musicskill','Sitamie',NULL,NULL),
 (19,'musicskill','Stīgu',NULL,NULL),
 (20,'musicskill','Taustiņu',NULL,NULL),
 (21,'musicskill','El. ģitāra',NULL,NULL),
 (22,'musicskill','Ģitāra',NULL,NULL),
 (23,'singskill','Koris',NULL,NULL),
 (24,'singskill','Grupa',NULL,NULL),
 (25,'singskill','Solo',NULL,NULL),
 (26,'sportskill','Aerobika',NULL,NULL),
 (27,'sportskill','Aikido',NULL,NULL),
 (28,'sportskill','Alpīnisms',NULL,NULL),
 (29,'sportskill','Armrestlings',NULL,NULL),
 (30,'sportskill','Ātrslidošana',NULL,NULL),
 (31,'sportskill','Austrumu cīņas',NULL,NULL),
 (32,'sportskill','Autokross',NULL,NULL),
 (33,'sportskill','Autošoseja',NULL,NULL),
 (34,'sportskill','Badmintons',NULL,NULL),
 (35,'sportskill','Basketbols',NULL,NULL),
 (36,'sportskill','Batuts',NULL,NULL),
 (37,'sportskill','Beisbols',NULL,NULL),
 (38,'sportskill','Bendijs',NULL,NULL),
 (39,'sportskill','Biatlons',NULL,NULL),
 (40,'sportskill','Biljards',NULL,NULL),
 (41,'sportskill','Bmx',NULL,NULL),
 (42,'sportskill','Bobslejs',NULL,NULL),
 (43,'sportskill','Boulings',NULL,NULL),
 (44,'sportskill','Bokss',NULL,NULL),
 (45,'sportskill','Brīvā cīņa',NULL,NULL),
 (46,'sportskill','Burāšana',NULL,NULL),
 (47,'sportskill','Capoeira',NULL,NULL),
 (48,'sportskill','Cīņa',NULL,NULL),
 (49,'sportskill','Daiļslidošana',NULL,NULL),
 (50,'sportskill','Dambrete',NULL,NULL),
 (51,'sportskill','Duatlons',NULL,NULL),
 (52,'sportskill','Džudo',NULL,NULL),
 (53,'sportskill','Enduro',NULL,NULL),
 (54,'sportskill','Fitness',NULL,NULL),
 (55,'sportskill','Florbols',NULL,NULL),
 (56,'sportskill','Formula 1',NULL,NULL),
 (57,'sportskill','Formula 3',NULL,NULL),
 (58,'sportskill','Frisbijs',NULL,NULL),
 (59,'sportskill','Frīstails',NULL,NULL),
 (60,'sportskill','Futbols',NULL,NULL),
 (61,'sportskill','Galda teniss',NULL,NULL),
 (62,'sportskill','Galda hokejs',NULL,NULL),
 (63,'sportskill','Golfs',NULL,NULL),
 (64,'sportskill','Grieķu - romiešu cīņa',NULL,NULL),
 (65,'sportskill','Handbols',NULL,NULL),
 (66,'sportskill','Hokejs',NULL,NULL),
 (67,'sportskill','Ielu vingrošana',NULL,NULL),
 (68,'sportskill','Izpletņlēkšana',NULL,NULL),
 (69,'sportskill','Jāšanas sports',NULL,NULL),
 (70,'sportskill','Kaitbordings',NULL,NULL),
 (71,'sportskill','Kalnu riteņbraukšana',NULL,NULL),
 (72,'sportskill','Kamaniņu sports',NULL,NULL),
 (73,'sportskill','Karate',NULL,NULL),
 (74,'sportskill','Kartings',NULL,NULL),
 (75,'sportskill','Kērlings',NULL,NULL),
 (76,'sportskill','Kikbokss',NULL,NULL),
 (77,'sportskill','Klinšu kāpšana',NULL,NULL),
 (78,'sportskill','Krikets',NULL,NULL),
 (79,'sportskill','Lauka hokejs',NULL,NULL),
 (80,'sportskill','Loka šaušana',NULL,NULL),
 (81,'sportskill','Mākslas vingrošana',NULL,NULL),
 (82,'sportskill','Minifutbols',NULL,NULL),
 (83,'sportskill','Minigolfs',NULL,NULL),
 (84,'sportskill','Modernā pieccīņa',NULL,NULL),
 (85,'sportskill','Motokross',NULL,NULL),
 (86,'sportskill','Motosports',NULL,NULL),
 (87,'sportskill','Motošoseja',NULL,NULL),
 (88,'sportskill','Mototriāls',NULL,NULL),
 (89,'sportskill','Mountain biking',NULL,NULL),
 (90,'sportskill','Mountainbords',NULL,NULL),
 (91,'sportskill','Niršana',NULL,NULL),
 (92,'sportskill','Novuss',NULL,NULL),
 (93,'sportskill','Orientēšanās sports',NULL,NULL),
 (94,'sportskill','Paukošana',NULL,NULL),
 (95,'sportskill','Peintbols',NULL,NULL),
 (96,'sportskill','Peldēšana',NULL,NULL),
 (97,'sportskill','Pludmales futbols',NULL,NULL),
 (98,'sportskill','Pludmales volejbols',NULL,NULL),
 (99,'sportskill','Pauerliftings',NULL,NULL),
 (100,'sportskill','Rallijkross',NULL,NULL),
 (101,'sportskill','Rallijs',NULL,NULL),
 (102,'sportskill','Regbijs',NULL,NULL),
 (103,'sportskill','Rollerslēpošana',NULL,NULL),
 (104,'sportskill','Sambo',NULL,NULL),
 (105,'sportskill','Sinhronā peldēšana',NULL,NULL),
 (106,'sportskill','Skeitbords',NULL,NULL),
 (107,'sportskill','Skijorings',NULL,NULL),
 (108,'sportskill','Skrituļslidošana',NULL,NULL),
 (109,'sportskill','Skvošs',NULL,NULL),
 (110,'sportskill','Slēpošana',NULL,NULL),
 (111,'sportskill','Slidošana',NULL,NULL),
 (112,'sportskill','Smaiļošana un kanoe',NULL,NULL),
 (113,'sportskill','Snovbords',NULL,NULL),
 (114,'sportskill','Snūkers',NULL,NULL),
 (115,'sportskill','Softbols',NULL,NULL),
 (116,'sportskill','Spēkavīru sacensības',NULL,NULL),
 (117,'sportskill','Spīdvejs',NULL,NULL),
 (118,'sportskill','Sporta dejas',NULL,NULL),
 (119,'sportskill','Šosejas riteņbraukšana',NULL,NULL),
 (120,'sportskill','Strītbols',NULL,NULL),
 (121,'sportskill','Svarbumbu celšana',NULL,NULL),
 (122,'sportskill','Svarcelšana',NULL,NULL),
 (123,'sportskill','Šahs',NULL,NULL),
 (124,'sportskill','Šaušana',NULL,NULL),
 (125,'sportskill','Šautriņu mešana (darts)',NULL,NULL),
 (126,'sportskill','Šorttreks',NULL,NULL),
 (127,'sportskill','Tautas sports',NULL,NULL),
 (128,'sportskill','Teikvando',NULL,NULL),
 (129,'sportskill','Telpu futbols',NULL,NULL),
 (130,'sportskill','Teniss',NULL,NULL),
 (131,'sportskill','Tramplīnlēkšana',NULL,NULL),
 (132,'sportskill','Triāls',NULL,NULL),
 (133,'sportskill','Triatlons',NULL,NULL),
 (134,'sportskill','Ūdensmotosports',NULL,NULL),
 (135,'sportskill','Ūdenspolo',NULL,NULL),
 (136,'sportskill','Ūdensslēpošana',NULL,NULL),
 (137,'sportskill','Veikbords',NULL,NULL),
 (138,'sportskill','Vieglatlētika',NULL,NULL),
 (139,'sportskill','Vindsērfings',NULL,NULL),
 (140,'sportskill','Vingrošana',NULL,NULL),
 (141,'sportskill','Virves vilkšana',NULL,NULL),
 (142,'sportskill','Volejbols',NULL,NULL),
 (143,'sportskill','Ziemas peldēšana',NULL,NULL),
 (144,'swimskill','1',NULL,NULL),
 (145,'swimskill','2',NULL,NULL),
 (146,'swimskill','3',NULL,NULL),
 (147,'swimskill','4',NULL,NULL),
 (148,'swimskill','5',NULL,NULL),
 (149,'swimskill','6',NULL,NULL),
 (150,'swimskill','7',NULL,NULL),
 (151,'swimskill','8',NULL,NULL),
 (152,'swimskill','9',NULL,NULL),
 (153,'swimskill','10',NULL,NULL),
 (155,'want_participate','Filmu projektos',NULL,NULL),
 (156,'want_participate','Reklāmu projektos',NULL,NULL),
 (157,'want_participate','Videoklipu projektos',NULL,NULL),
 (158,'want_participate','Teātra projektos',NULL,NULL),
 (159,'want_participate','Nekomerciālos projektos',NULL,NULL),
 (160,'want_participate','Visur, kur varat piedāvāt',NULL,NULL),
 (161,'dont_want_participate','Alkoholisko izstrādājumu reklāmās',NULL,NULL),
 (162,'dont_want_participate','Tabakas izstrādājumu reklāmās',NULL,NULL),
 (163,'dont_want_participate','Politiskajās reklāmās',NULL,NULL),
 (164,'dont_want_participate','Vietējās reklāmās',NULL,NULL),
 (165,'interested_in','Tikai galvenās lomas',NULL,NULL),
 (166,'interested_in','Otrā plāna lomas',NULL,NULL),
 (167,'interested_in','Masu skati',NULL,NULL),
 (168,'languageskill','Latviešu-dzimtā valoda',NULL,NULL),
 (169,'languageskill','Latviešu-ļoti labi',NULL,NULL),
 (170,'languageskill','Latviešu-labi',NULL,NULL),
 (171,'languageskill','Latviešu-pamatzināšanas',NULL,NULL),
 (172,'languageskill','Krievu-dzimtā valoda',NULL,NULL),
 (173,'languageskill','Krievu-ļoti labi',NULL,NULL),
 (174,'languageskill','Krievu-labi',NULL,NULL),
 (175,'languageskill','Krievu-pamatzināšanas',NULL,NULL),
 (176,'languageskill','Angļu-dzimtā valoda',NULL,NULL),
 (177,'languageskill','Angļu-ļoti labi',NULL,NULL),
 (178,'languageskill','Angļu-labi',NULL,NULL),
 (179,'languageskill','Angļu-pamatzināšanas',NULL,NULL),
 (180,'languageskill','Vācu-dzimtā valoda',NULL,NULL),
 (181,'languageskill','Vācu-ļoti labi',NULL,NULL),
 (182,'languageskill','Vācu-labi',NULL,NULL),
 (183,'languageskill','Vācu-pamatzināšanas',NULL,NULL),
 (184,'city','Rīga',NULL,NULL),
 (185,'city','Ainaži',NULL,NULL),
 (186,'city','Aizkraukle',NULL,NULL),
 (187,'city','Aizpute',NULL,NULL),
 (188,'city','Aknīste',NULL,NULL),
 (189,'city','Aloja',NULL,NULL),
 (190,'city','Alūksne',NULL,NULL),
 (191,'city','Ape',NULL,NULL),
 (192,'city','Auce',NULL,NULL),
 (193,'city','Baldone',NULL,NULL),
 (194,'city','Baloži',NULL,NULL),
 (195,'city','Balvi',NULL,NULL),
 (196,'city','Bauska',NULL,NULL),
 (197,'city','Brocēni',NULL,NULL),
 (198,'city','Cēsis',NULL,NULL),
 (199,'city','Cesvaine',NULL,NULL),
 (200,'city','Dagda',NULL,NULL),
 (201,'city','Daugavpils',NULL,NULL),
 (202,'city','Dobele',NULL,NULL),
 (203,'city','Durbe',NULL,NULL),
 (204,'city','Grobiņa',NULL,NULL),
 (205,'city','Gulbene',NULL,NULL),
 (206,'city','Ikšķile',NULL,NULL),
 (207,'city','Ilūkste',NULL,NULL),
 (208,'city','Jaunjelgava',NULL,NULL),
 (209,'city','Jēkabpils',NULL,NULL),
 (210,'city','Jelgava',NULL,NULL),
 (211,'city','Jūrmala',NULL,NULL),
 (212,'city','Kandava',NULL,NULL),
 (213,'city','Kārsava',NULL,NULL),
 (214,'city','Krāslava',NULL,NULL),
 (215,'city','Kuldīga',NULL,NULL),
 (216,'city','Ķegums',NULL,NULL),
 (217,'city','Lielvārde',NULL,NULL),
 (218,'city','Liepāja',NULL,NULL),
 (219,'city','Līgatne',NULL,NULL),
 (220,'city','Limbaži',NULL,NULL),
 (221,'city','Līvāni',NULL,NULL),
 (222,'city','Lubāna',NULL,NULL),
 (223,'city','Ludza',NULL,NULL),
 (224,'city','Madona',NULL,NULL),
 (225,'city','Mazsalaca',NULL,NULL),
 (226,'city','Ogre',NULL,NULL),
 (227,'city','Olaine',NULL,NULL),
 (228,'city','Pāvilosta',NULL,NULL),
 (229,'city','Piltene',NULL,NULL),
 (230,'city','Pļaviņas',NULL,NULL),
 (231,'city','Preiļi',NULL,NULL),
 (232,'city','Priekule',NULL,NULL),
 (233,'city','Rēzekne',NULL,NULL),
 (234,'city','Rūjiena',NULL,NULL),
 (235,'city','Sabile',NULL,NULL),
 (236,'city','Salacgrīva',NULL,NULL),
 (237,'city','Salaspils',NULL,NULL),
 (238,'city','Saldus',NULL,NULL),
 (239,'city','Saulkrasti',NULL,NULL),
 (240,'city','Seda',NULL,NULL),
 (241,'city','Sigulda',NULL,NULL),
 (242,'city','Skrunda',NULL,NULL),
 (243,'city','Smiltene',NULL,NULL),
 (244,'city','Staicele',NULL,NULL),
 (245,'city','Stende',NULL,NULL),
 (246,'city','Strenči',NULL,NULL),
 (247,'city','Subate',NULL,NULL),
 (248,'city','Talsi',NULL,NULL),
 (249,'city','Tukums',NULL,NULL),
 (250,'city','Valdemārpils',NULL,NULL),
 (251,'city','Valka',NULL,NULL),
 (252,'city','Valmiera',NULL,NULL),
 (253,'city','Vangaži',NULL,NULL),
 (254,'city','Varakļāni',NULL,NULL),
 (255,'city','Ventspils',NULL,NULL),
 (256,'city','Viesīte',NULL,NULL),
 (257,'city','Viļaka',NULL,NULL),
 (258,'city','Viļāni',NULL,NULL),
 (259,'city','Zilupe',NULL,NULL),
 (260,'haircolor','Melna',NULL,NULL),
 (261,'haircolor','Pelēka',NULL,NULL),
 (262,'haircolor','Blonda',NULL,NULL),
 (263,'haircolor','Brūna',NULL,NULL),
 (264,'haircolor','Gaiši brūna',NULL,NULL),
 (265,'haircolor','Sarkana',NULL,NULL),
 (266,'haircolor','Rozā',NULL,NULL),
 (267,'haircolor','Tumši blonda',NULL,NULL),
 (268,'haircolor','Tumši brūna',NULL,NULL),
 (269,'haircolor','Zelta blonda',NULL,NULL),
 (270,'haircolor','Smilšu blonda',NULL,NULL),
 (271,'haircolor','Cita',NULL,NULL),
 (272,'haircolor','Nav matu',NULL,NULL),
 (273,'eyecolor','Brūna',NULL,NULL),
 (274,'eyecolor','Gaiši brūna',NULL,NULL),
 (275,'eyecolor','Zila',NULL,NULL),
 (276,'eyecolor','Tumši zila',NULL,NULL),
 (277,'eyecolor','Gaiši zila',NULL,NULL),
 (278,'eyecolor','Pelēka',NULL,NULL),
 (279,'eyecolor','Tumši pelēka',NULL,NULL),
 (280,'eyecolor','Pelēkizaļa',NULL,NULL),
 (281,'eyecolor','Pelēkbrūna',NULL,NULL),
 (282,'eyecolor','Zaļa',NULL,NULL),
 (283,'eyecolor','Zaļganbrūnas',NULL,NULL),
 (284,'subspeciality','Amatieraktieris',NULL,NULL),
 (285,'subspeciality','Mīms',NULL,NULL),
 (286,'subspeciality','Statists',NULL,NULL),
 (287,'subspeciality','Modelis',NULL,NULL),
 (288,'subspeciality','Mūziķis',NULL,NULL),
 (289,'subspeciality','Dejotājs',NULL,NULL),
 (290,'subspeciality','Radiobalss',NULL,NULL),
 (291,'subspeciality','Kaskadieris',NULL,NULL),
 (292,'subspeciality','Cirka mākslinieks',NULL,NULL),
 (293,'eyecolor','Pelēkzila',NULL,NULL),
 (294,'eyecolor','Cita',NULL,NULL),
 (295,'voice','Soprāns',NULL,NULL),
 (296,'voice','Mecosoprāns',NULL,NULL),
 (297,'voice','Alts',NULL,NULL),
 (298,'voice','Tenors',NULL,NULL),
 (299,'voice','Baritons',NULL,NULL),
 (300,'voice','Bass',NULL,NULL),
 (301,'voice','Cits',NULL,NULL),
 (302,'current_occupation','Skolnieks',NULL,NULL),
 (303,'current_occupation','Students',NULL,NULL),
 (304,'current_occupation','Strādājošs',NULL,NULL),
 (305,'current_occupation','Bezdarbnieks',NULL,NULL),
 (306,'current_occupation','Mākslinieks',NULL,NULL),
 (307,'current_occupation','Cits',NULL,NULL);
CREATE INDEX ix_skill_person_id ON skill (person_id);
CREATE INDEX ix_skill_classifier_id ON skill (classifier_id);
CREATE INDEX ix_person_surname ON person (surname);
CREATE INDEX ix_person_name ON person (name);
CREATE INDEX ix_document_person_id ON document (person_id);
CREATE INDEX ix_classifier_tag_ru ON classifier (tag_ru);
CREATE INDEX ix_classifier_tag_lv ON classifier (tag_lv);
CREATE INDEX ix_classifier_tag_en ON classifier (tag_en);
CREATE INDEX ix_classifier_category ON classifier (category);
COMMIT;
